### PR TITLE
Just in time with js

### PR DESCRIPTION
**Pull request by dormi**

### CODE REVIEW

**Comment by etdsoft** [comment]
* One thing that jumps at me is that you have an `Issues::NodesController`, but inside it what you care about is Evidence, and you're rendering `issues/evidence_content`.

* There are no specs.

* I see one request every time I click on the evidence tab (so we're not caching already downloaded pieces of evidence), this may not be a bad thing if latency is low, but it seems wasteful if we're going to cache the evidence.

* My browser console is full of `undefined` calls? One for each click on an Evidence instance, but it seems it only happens the first time I click on the links?

evidence-js-01

**Comment by dormi** [comment]
Yet another weird case, due to using "js fetch"
captura de pantalla 2018-04-26 a las 8 31 42
:

**Comment by dormi** [comment]
> I see one request every time I click on the evidence tab (so we're not caching already downloaded pieces of evidence), this may not be a bad thing if latency is low, but it seems wasteful if we're going to cache the evidence.

This is unintended, caused by the same error that displayed all those "undefined" to the console.
The idea is to make request when clicking on a node tab, not in evidence tabs.
Fixed in https://github.com/dradis/dradis-ce/pull/235/commits/1ac3111e9236a1124e00614fffe29b0be501feb6

**Comment by etdsoft** [comment]
The Ajax call triggers the following request:

```
Started GET "/issues/130/nodes/13" for 127.0.0.1 at 2018-05-03 16:38:22 +0200
Processing by Issues::NodesController#show as */*
  Parameters: {"issue_id"=>"130", "id"=>"13"}
  Node Load (0.4ms)  SELECT  "nodes".* FROM "nodes" WHERE "nodes"."label" = ? AND "nodes"."type_id" = ? LIMIT ?  [["label", "All issues"], ["type_id", 3], ["LIMIT", 1]]
   (0.1ms)  begin transaction
  Issue Load (1.3ms)  SELECT notes.id, notes.author, notes.text, count(evidence.id) as affected_count, notes.created_at, notes.updated_at FROM "notes" LEFT OUTER JOIN evidence on notes.id = evidence.issue_id WHERE "notes"."node_id" = ? GROUP BY notes.id  [["node_id", 10]]
  Tagging Load (0.8ms)  SELECT "taggings".* FROM "taggings" WHERE "taggings"."taggable_type" = ? AND "taggings"."taggable_id" IN (130, 131, 132, 133, 134, 135, 136, 137, 138, 139)  [["taggable_type", "Note"]]
   (0.1ms)  commit transaction
  Issue Load (0.2ms)  SELECT  "notes".* FROM "notes" WHERE "notes"."id" = ? LIMIT ?  [["id", 130], ["LIMIT", 1]]
  Node Load (0.8ms)  SELECT  nodes.id, label, type_id, count(evidence.id) as evidence_count, nodes.updated_at FROM "nodes" INNER JOIN "evidence" ON "evidence"."node_id" = "nodes"."id" WHERE (evidence.issue_id = '130' and nodes.id = '13') ORDER BY "nodes"."id" ASC LIMIT ?  [["LIMIT", 1]]
  Rendering issues/nodes/show.html.erb
  Evidence Load (0.3ms)  SELECT  "evidence".* FROM "evidence" WHERE "evidence"."issue_id" = 130 AND "evidence"."node_id" = 13 ORDER BY "evidence"."id" ASC LIMIT ?  [["LIMIT", 1]]
  Evidence Load (0.8ms)  SELECT "evidence".* FROM "evidence" WHERE "evidence"."issue_id" = 130 AND "evidence"."node_id" = 13
  Rendered issues/nodes/_evidence.html.erb (92.6ms)
  Rendered issues/nodes/show.html.erb (127.4ms)
Completed 200 OK in 191ms (Views: 168.7ms | ActiveRecord: 4.9ms)
```

Comments (numbering SQL queries from 1 onward):

- Why are SQL#1 (All issues node load), and SQL#2 (issues load) needed?
- Why are we loading taggings in this request (SQL#3)?
- Why are we loading the Issue content (SQL#4)?
- Why are SQL#6 and SQL#7 happening?

**Comment by dormi** [comment]
@etdsoft used `skip_before_action` to remove parent controller filters.

Now it should look like:

```
Started GET "/issues/1/nodes/107" for ::1 at 2018-05-07 10:29:19 +0100
Processing by Issues::NodesController#show as */*
  Parameters: {"issue_id"=>"1", "id"=>"107"}
  Node Load (0.3ms)  SELECT  nodes.id, label, type_id, count(evidence.id) as evidence_count, nodes.updated_at FROM "nodes" INNER JOIN "evidence" ON "evidence"."node_id" = "nodes"."id" WHERE (evidence.issue_id = '1' and nodes.id = '107') ORDER BY "nodes"."id" ASC LIMIT ?  [["LIMIT", 1]]
  Rendering issues/nodes/show.html.erb
  Evidence Load (0.2ms)  SELECT  "evidence".* FROM "evidence" WHERE "evidence"."issue_id" = ? AND "evidence"."node_id" = 107 ORDER BY "evidence"."id" ASC LIMIT ?  [["issue_id", 1], ["LIMIT", 1]]
  Rendered issues/nodes/_evidence.html.erb (3.2ms)
  Rendered issues/nodes/show.html.erb (15.1ms)
Completed 200 OK in 31ms (Views: 27.3ms | ActiveRecord: 0.5ms)
```

**Comment by dormi** [comment]
@etdsoft you were right.

**Pull request merged**
