### PR TITLE
Remove :resque from queue adapter app config

### PR DESCRIPTION
**Pull request by etdsoft**
Try to simplify CE deployment by making use of ActiveJob's in-memory implementation.

### How to test
1. Make sure neither Redis or Resque are running.
2. Upload a big Nessus file (you can copy the <ReportItem> section multiple times from a smaller file).
3. The in-memory background worker should kick in and the file should be parsed as usual.
4. using the burp uploader, upload many times this file: https://github.com/dradis/dradis-saint/blob/initial-implementation/spec/fixtures/files/saint_metasploitable_sample.xml
Assert that even the upload does not work, in the logs we don't see any `SQLite3::BusyException` exceptions

### CODE REVIEW

**Comment by dormi** [comment]
Sometimes I see this error:
```
[ActiveJob] [UploadJob] [547868c8-5409-4e56-949b-ebb3f956e5b9]    (0.1ms)  rollback transaction
  SQL (0.6ms)  INSERT INTO "logs" ("uid", "text", "created_at", "updated_at") VALUES (?, ?, ?, ?)  [["uid", 11], ["text", "Job id is 547868c8-5409-4e56-949b-ebb3f956e5b9."], ["created_at", "2017-10-18 10:47:25.294942"], ["updated_at", "2017-10-18 10:47:25.294942"]]
Processing by UploadController#status as JS
[ActiveJob] [UploadJob] [547868c8-5409-4e56-949b-ebb3f956e5b9] Error performing UploadJob (Job ID: 547868c8-5409-4e56-949b-ebb3f956e5b9) from Async(dradis_upload) in 593.48ms: ActiveRecord::StatementInvalid (SQLite3::BusyException: database is locked: INSERT INTO "logs" ("uid", "text", "created_at", "updated_at") VALUES (?, ?, ?, ?)):
```

For instance, when uploading https://github.com/dradis/dradis-burp/blob/master/spec/fixtures/files/without-base64.xml

Not sure if this gem could help: https://github.com/dradis/dradis-burp/blob/master/spec/fixtures/files/without-base64.xml

**Comment by etdsoft** [comment]
So the first thing I'm getting when uploading that file is:

> [15:01:27] Burp input contains HTTP request / response data that hasn't been Base64-encoded. Please re-export your scanner results making sure the Base-64 encode option is selected.

... which seems about right?

Also, we don't want to remove resque to add sucker_punch, we're aiming for vanilla ActiveJob.

It seems to me that this is a SQLite limitation (dealing with different threads accessing the DB concurrently). StackOverflow reckons that we can sidestep the issue by increasing the time out, can you confirm if this fixes the issue?

```
development:
  adapter: sqlite3
  database: db/development.sqlite3
  timeout: 10000
```


https://stackoverflow.com/a/739037

**Comment by dormi** [comment]
I am testing this by changing this code in `UploadController`:
```ruby
  #if Rails.env.production? || (File.size(attachment.fullpath) > 1024*1024)
     process_upload_background(attachment: attachment)
  #else
  #  process_upload_inline(attachment: attachment)
  #end
```
Then using burp uploader, I try to upload a saint file: https://github.com/dradis/dradis-saint/blob/initial-implementation/spec/fixtures/files/saint_metasploitable_sample.xml
(It should display an error, as it does in `master` branch)

No luck increasing that `timeout`. 
Neither increasing the `pool`.
```yml
development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 20
  timeout: 20000
```

Neither using transactions in the `Log` model:
```ruby
class Log < ApplicationRecord
  def write(trace = nil, &block)
    text = trace.nil? ? yield : trace
    Log.transaction { Log.create(attributes.merge(text: text)) }
  end

  alias :info :write
  alias :debug :write
  alias :error :write
  alias :fatal :write

  def read
    Log.transaction { "[#{created_at.strftime('%H:%M:%S')}]  #{text}" }
  end
end
```

Full stack trace:
```
::1 - - [19/Oct/2017:10:43:29 WEST] "POST /upload.js HTTP/1.1" 200 348
http://localhost:3000/upload -> /upload.js
Started POST "/upload/parse" for ::1 at 2017-10-19 10:43:29 +0100
Processing by UploadController#parse as JS
  Parameters: {"item_id"=>"39", "uploader"=>"Dradis::Plugins::Burp", "file"=>"saint_metasploitable_sample.xml"}
  Configuration Load (0.7ms)  SELECT  "configurations".* FROM "configurations" WHERE "configurations"."name" = ? LIMIT ?  [["name", "admin:plugins:uploads_node"], ["LIMIT", 1]]
  Node Load (0.8ms)  SELECT  "nodes".* FROM "nodes" WHERE "nodes"."label" = ? LIMIT ?  [["label", "Uploaded files"], ["LIMIT", 1]]
  Node Exists (0.4ms)  SELECT  1 AS one FROM "nodes" WHERE "nodes"."id" = ? LIMIT ?  [["id", 3], ["LIMIT", 1]]
[ActiveJob] Enqueued UploadJob (Job ID: e64878ad-b5ee-4212-bb9b-e5fe92af1fa2) to Async(dradis_upload) with arguments: {:file=>"/Users/xavi/Projects/dradis/dradis-ce/attachments/3/saint_metasploitable_sample.xml", :plugin_name=>"Dradis::Plugins::Burp", :uid=>39}
[ActiveJob] [UploadJob] [e64878ad-b5ee-4212-bb9b-e5fe92af1fa2] Performing UploadJob (Job ID: e64878ad-b5ee-4212-bb9b-e5fe92af1fa2) from Async(dradis_upload) with arguments: {:file=>"/Users/xavi/Projects/dradis/dradis-ce/attachments/3/saint_metasploitable_sample.xml", :plugin_name=>"Dradis::Plugins::Burp", :uid=>39}
   (0.1ms)  begin transaction
[ActiveJob] [UploadJob] [e64878ad-b5ee-4212-bb9b-e5fe92af1fa2]    (0.0ms)  begin transaction
  SQL (0.7ms)  INSERT INTO "logs" ("uid", "text", "created_at", "updated_at") VALUES (?, ?, ?, ?)  [["uid", 39], ["text", "Enqueueing job to start in the background."], ["created_at", "2017-10-19 09:43:29.112665"], ["updated_at", "2017-10-19 09:43:29.112665"]]
   (1.6ms)  commit transaction
[ActiveJob] [UploadJob] [e64878ad-b5ee-4212-bb9b-e5fe92af1fa2]   SQL (833.7ms)  INSERT INTO "logs" ("uid", "text", "created_at", "updated_at") VALUES (?, ?, ?, ?)  [["uid", 39], ["text", "Running Ruby version 2.4.1"], ["created_at", "2017-10-19 09:43:29.115059"], ["updated_at", "2017-10-19 09:43:29.115059"]]
   (0.1ms)  begin transaction
[ActiveJob] [UploadJob] [e64878ad-b5ee-4212-bb9b-e5fe92af1fa2]    (0.1ms)  rollback transaction
  SQL (0.4ms)  INSERT INTO "logs" ("uid", "text", "created_at", "updated_at") VALUES (?, ?, ?, ?)  [["uid", 39], ["text", "Job id is e64878ad-b5ee-4212-bb9b-e5fe92af1fa2."], ["created_at", "2017-10-19 09:43:29.958027"], ["updated_at", "2017-10-19 09:43:29.958027"]]
Started GET "/upload/status?item_id=39&after=0&_=1508406203932" for ::1 at 2017-10-19 10:43:29 +0100
[ActiveJob] [UploadJob] [e64878ad-b5ee-4212-bb9b-e5fe92af1fa2] Error performing UploadJob (Job ID: e64878ad-b5ee-4212-bb9b-e5fe92af1fa2) from Async(dradis_upload) in 848.74ms: ActiveRecord::StatementInvalid (SQLite3::BusyException: database is locked: INSERT INTO "logs" ("uid", "text", "created_at", "updated_at") VALUES (?, ?, ?, ?)):
/Users/xavi/.rvm/gems/ruby-2.4.1/gems/sqlite3-1.3.13/lib/sqlite3/statement.rb:108:in `step'
/Users/xavi/.rvm/gems/ruby-2.4.1/gems/sqlite3-1.3.13/lib/sqlite3/statement.rb:108:in `block in each'
/Users/xavi/.rvm/gems/ruby-2.4.1/gems/sqlite3-1.3.13/lib/sqlite3/statement.rb:107:in `loop'
/Users/xavi/.rvm/gems/ruby-2.4.1/gems/sqlite3-1.3.13/lib/sqlite3/statement.rb:107:in `each'
/Users/xavi/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.4/lib/active_record/connection_adapters/sqlite3_adapter.rb:218:in `to_a'
/Users/xavi/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.4/lib/active_record/connection_adapters/sqlite3_adapter.rb:218:in `block (2 levels) in exec_query'
/Users/xavi/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.4/lib/active_support/dependencies/interlock.rb:46:in `block in permit_concurrent_loads'
/Users/xavi/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.4/lib/active_support/concurrency/share_lock.rb:185:in `yield_shares'
/Users/xavi/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.4/lib/active_support/dependencies/interlock.rb:45:in `permit_concurrent_loads'
/Users/xavi/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.4/lib/active_record/connection_adapters/sqlite3_adapter.rb:209:in `block in exec_query'
/Users/xavi/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract_adapter.rb:612:in `block (2 levels) in log'
/Users/xavi/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
/Users/xavi/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract_adapter.rb:611:in `block in log'
/Users/xavi/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.4/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
/Users/xavi/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract_adapter.rb:603:in `log'
/Users/xavi/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.4/lib/active_record/connection_adapters/sqlite3_adapter.rb:208:in `exec_query'
/Users/xavi/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/database_statements.rb:102:in `exec_insert'
/Users/xavi/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/database_statements.rb:133:in `insert'
/Users/xavi/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/query_cache.rb:17:in `insert'
/Users/xavi/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.4/lib/active_record/relation.rb:61:in `insert'
/Users/xavi/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.4/lib/active_record/persistence.rb:589:in `_create_record'
/Users/xavi/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.4/lib/active_record/counter_cache.rb:178:in `_create_record'
/Users/xavi/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.4/lib/active_record/locking/optimistic.rb:76:in `_create_record'
/Users/xavi/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.4/lib/active_record/attribute_methods/dirty.rb:296:in `_create_record'
/Users/xavi/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.4/lib/active_record/callbacks.rb:340:in `block in _create_record'
/Users/xavi/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.4/lib/active_support/callbacks.rb:131:in `run_callbacks'
/Users/xavi/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.4/lib/active_support/callbacks.rb:827:in `_run_create_callbacks'
/Users/xavi/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.4/lib/active_record/callbacks.rb:340:in `_create_record'
/Users/xavi/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.4/lib/active_record/timestamp.rb:95:in `_create_record'
/Users/xavi/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.4/lib/active_record/persistence.rb:563:in `create_or_update'
/Users/xavi/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.4/lib/active_record/callbacks.rb:336:in `block in create_or_update'
/Users/xavi/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.4/lib/active_support/callbacks.rb:97:in `run_callbacks'
/Users/xavi/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.4/lib/active_support/callbacks.rb:827:in `_run_save_callbacks'
/Users/xavi/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.4/lib/active_record/callbacks.rb:336:in `create_or_update'
/Users/xavi/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.4/lib/active_record/persistence.rb:129:in `save'
/Users/xavi/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.4/lib/active_record/validations.rb:44:in `save'
/Users/xavi/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.4/lib/active_record/attribute_methods/dirty.rb:35:in `save'
/Users/xavi/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.4/lib/active_record/transactions.rb:308:in `block (2 levels) in save'
/Users/xavi/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.4/lib/active_record/transactions.rb:384:in `block in with_transaction_returning_status'
/Users/xavi/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/database_statements.rb:233:in `transaction'
/Users/xavi/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.4/lib/active_record/transactions.rb:210:in `transaction'
/Users/xavi/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.4/lib/active_record/transactions.rb:381:in `with_transaction_returning_status'
/Users/xavi/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.4/lib/active_record/transactions.rb:308:in `block in save'
/Users/xavi/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.4/lib/active_record/transactions.rb:323:in `rollback_active_record_state!'
/Users/xavi/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.4/lib/active_record/transactions.rb:307:in `save'
/Users/xavi/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.4/lib/active_record/suppressor.rb:42:in `save'
/Users/xavi/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.4/lib/active_record/persistence.rb:34:in `create'
/Users/xavi/Projects/dradis/dradis-ce/app/models/log.rb:4:in `block in write'
/Users/xavi/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/database_statements.rb:235:in `block in transaction'
/Users/xavi/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/transaction.rb:194:in `block in within_new_transaction'
/Users/xavi/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
/Users/xavi/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/transaction.rb:191:in `within_new_transaction'
/Users/xavi/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/database_statements.rb:235:in `transaction'
/Users/xavi/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.4/lib/active_record/transactions.rb:210:in `transaction'
/Users/xavi/Projects/dradis/dradis-ce/app/models/log.rb:4:in `write'
/Users/xavi/Projects/dradis/dradis-ce/app/jobs/upload_job.rb:7:in `perform'
/Users/xavi/.rvm/gems/ruby-2.4.1/gems/activejob-5.1.4/lib/active_job/execution.rb:37:in `block in perform_now'
/Users/xavi/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.4/lib/active_support/callbacks.rb:108:in `block in run_callbacks'
/Users/xavi/.rvm/gems/ruby-2.4.1/gems/i18n-0.9.0/lib/i18n.rb:265:in `with_locale'
/Users/xavi/.rvm/gems/ruby-2.4.1/gems/activejob-5.1.4/lib/active_job/translation.rb:7:in `block (2 levels) in <module:Translation>'
/Users/xavi/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.4/lib/active_support/callbacks.rb:117:in `instance_exec'
/Users/xavi/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.4/lib/active_support/callbacks.rb:117:in `block in run_callbacks'
/Users/xavi/.rvm/gems/ruby-2.4.1/gems/activejob-5.1.4/lib/active_job/logging.rb:24:in `block (4 levels) in <module:Logging>'
/Users/xavi/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.4/lib/active_support/notifications.rb:166:in `block in instrument'
/Users/xavi/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.4/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
/Users/xavi/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.4/lib/active_support/notifications.rb:166:in `instrument'
/Users/xavi/.rvm/gems/ruby-2.4.1/gems/activejob-5.1.4/lib/active_job/logging.rb:23:in `block (3 levels) in <module:Logging>'
/Users/xavi/.rvm/gems/ruby-2.4.1/gems/activejob-5.1.4/lib/active_job/logging.rb:44:in `block in tag_logger'
/Users/xavi/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.4/lib/active_support/tagged_logging.rb:69:in `block in tagged'
/Users/xavi/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.4/lib/active_support/tagged_logging.rb:26:in `tagged'
/Users/xavi/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.4/lib/active_support/tagged_logging.rb:69:in `tagged'
/Users/xavi/.rvm/gems/ruby-2.4.1/gems/activejob-5.1.4/lib/active_job/logging.rb:44:in `tag_logger'
/Users/xavi/.rvm/gems/ruby-2.4.1/gems/activejob-5.1.4/lib/active_job/logging.rb:20:in `block (2 levels) in <module:Logging>'
/Users/xavi/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.4/lib/active_support/callbacks.rb:117:in `instance_exec'
/Users/xavi/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.4/lib/active_support/callbacks.rb:117:in `block in run_callbacks'
/Users/xavi/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.4/lib/active_support/callbacks.rb:135:in `run_callbacks'
/Users/xavi/.rvm/gems/ruby-2.4.1/gems/activejob-5.1.4/lib/active_job/execution.rb:33:in `perform_now'
/Users/xavi/.rvm/gems/ruby-2.4.1/gems/activejob-5.1.4/lib/active_job/execution.rb:22:in `block in execute'
/Users/xavi/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.4/lib/active_support/callbacks.rb:108:in `block in run_callbacks'
/Users/xavi/.rvm/gems/ruby-2.4.1/gems/activejob-5.1.4/lib/active_job/railtie.rb:26:in `block (4 levels) in <class:Railtie>'
/Users/xavi/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.4/lib/active_support/execution_wrapper.rb:85:in `wrap'
/Users/xavi/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.4/lib/active_support/reloader.rb:68:in `block in wrap'
/Users/xavi/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.4/lib/active_support/execution_wrapper.rb:85:in `wrap'
/Users/xavi/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.4/lib/active_support/reloader.rb:67:in `wrap'
/Users/xavi/.rvm/gems/ruby-2.4.1/gems/activejob-5.1.4/lib/active_job/railtie.rb:25:in `block (3 levels) in <class:Railtie>'
/Users/xavi/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.4/lib/active_support/callbacks.rb:117:in `instance_exec'
/Users/xavi/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.4/lib/active_support/callbacks.rb:117:in `block in run_callbacks'
/Users/xavi/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.4/lib/active_support/callbacks.rb:135:in `run_callbacks'
/Users/xavi/.rvm/gems/ruby-2.4.1/gems/activejob-5.1.4/lib/active_job/execution.rb:20:in `execute'
/Users/xavi/.rvm/gems/ruby-2.4.1/gems/activejob-5.1.4/lib/active_job/queue_adapters/async_adapter.rb:68:in `perform'
/Users/xavi/.rvm/gems/ruby-2.4.1/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
/Users/xavi/.rvm/gems/ruby-2.4.1/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
/Users/xavi/.rvm/gems/ruby-2.4.1/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
/Users/xavi/.rvm/gems/ruby-2.4.1/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
/Users/xavi/.rvm/gems/ruby-2.4.1/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
/Users/xavi/.rvm/gems/ruby-2.4.1/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
   (0.7ms)  commit transaction
Processing by UploadController#status as JS
Completed 200 OK in 870ms (ActiveRecord: 5.5ms)
```

**Comment by etdsoft** [comment]
Are the SQlite3 concerns gone @dormi ?

**Comment by dormi** [comment]
@etdsoft Yes, I think so

**Pull request merged**
