### PR TITLE
Comments must preserve linebreaks and white space

### PR DESCRIPTION
**Pull request by dormi**
This is the problem we want to fix:
preview-full-comments

### CODE REVIEW

**Comment by georgemillo** [comment]
The linebreaks look fine and I agree that `<pre>` is the way to go - but I don't like how each comment now takes up much more space:

Before:
screen shot 2018-07-18 at 11 12 42

After:
screen shot 2018-07-18 at 11 12 54

Can we remove the extra padding, especially from the bottom?

**Comment by dormi** [comment]
@georgemillo tried to fix it. 
Also looks like the comment bg color was a bit different. Fixed that too.

**Comment by etdsoft** [comment]
what's wrong with:

http://api.rubyonrails.org/classes/ActionView/Helpers/TextHelper.html#method-i-simple_format

**Comment by dormi** [comment]
@etdsoft 

> what's wrong with:
   http://api.rubyonrails.org/classes/ActionView/Helpers/TextHelper.html#method-i-simple_format

The white space (more than 1).
Using a `<pre>` we can keep line breaks and white space.

**Comment by dormi** [comment]
closing in favor of https://github.com/dradis/dradis-ce/pull/313

**Pull request closed without merging**
